{% set version = "0.13.0" %}
{% set sha256 = "b73e67d71b5954c3fbda1cbd97c20342e93073915cde5ece5d8b9d25614d8416" %}

package:
  name: scikit-build
  version: {{ version }}

source:
  url: https://github.com/scikit-build/scikit-build/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - cmake
    - ninja
    - pip
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - packaging
    - pip
    - python
    - setuptools
    - wheel
  run:
    - cmake
    - distro
    - packaging
    - python
    - ninja
    - setuptools
    - wheel

test:
  imports:
    - skbuild
  source_files:
    - tests/*
  requires:
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('cxx') }}  # [unix]
    - make  # [unix]
    - mock
    - path.py
    - pytest
    - pytest-mock
    - pytest-cov
    - pytest-runner
    - six
    - git
    - cmake
    - ninja
    - cython
    - requests

about:
  home: http://github.com/scikit-build/scikit-build
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Improved build system generator for CPython C extensions.
  doc_url: http://scikit-build.readthedocs.org
  dev_url: http://github.com/scikit-build/scikit-build

extra:
  recipe-maintainers:
    - isuruf
    - scopatz
    - jcfr
    - msarahan
