{% set version = "0.15.0" %}
{% set sha256 = "e723cd0f3489a042370b9ea988bbb9cfd7725e8b25b20ca1c7981821fcf65fb9" %}

package:
  name: scikit-build
  version: {{ version }}

source:
  url: https://github.com/scikit-build/scikit-build/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python

requirements:
  host:
    - packaging
    - pip
    - python
    - setuptools
    - setuptools_scm
    - wheel
  run:
    - cmake
    - distro
    - packaging
    - python
    - ninja
    - setuptools
    - wheel

test:
  imports:
    - skbuild
  source_files:
    - tests/*
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make  # [unix]
    - mock
    - path.py
    - pip
    - pytest
    - pytest-mock
    - pytest-cov
    - six
    - git
    - cython
    - requests

about:
  home: http://github.com/scikit-build/scikit-build
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Improved build system generator for CPython C extensions.
  doc_url: http://scikit-build.readthedocs.org
  dev_url: http://github.com/scikit-build/scikit-build

extra:
  recipe-maintainers:
    - isuruf
    - scopatz
    - jcfr
    - msarahan
