{% set name = "scikit-build" %}
{% set version = "0.18.1" %}
{% set sha256 = "a4152ac5a084d499c28a7797be0628d8366c336e2fb0e1a063eb32e55efcb8e7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scikit_build-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - hatchling
    - hatch-fancy-pypi-readme
    - hatch-vcs
  run:
    - python
    - cmake
    - distro
    - make  # [not win]
    - packaging
    # requires distutils.dir_util._path_created which was removed in setuptools 75
    - setuptools >=42.0.0,<75.0.0
    - wheel >=0.32.0
    - tomli # [py<311]

test:
  imports:
    - skbuild
  source_files:
    - tests/*
    - pyproject.toml
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - cython
    - git
    - make  # [not win]
    - ninja
    - path.py >=11.5.0
    - pip
    - python-build
    - pytest >=6.0.0
    - pytest-mock >=1.10.4
    - requests
    - virtualenv

about:
  home: https://github.com/scikit-build/scikit-build
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Improved build system generator for CPython C extensions.
  description: |
    scikit-build is an improved build system generator for CPython
    C/C++/Fortran/Cython extensions. It provides better support for additional
    compilers, build systems, cross compilation, and locating dependencies and
    their associated build requirements. The scikit-build package is
    fundamentally just glue between the setuptools Python module and CMake.

  doc_url: https://scikit-build.readthedocs.org
  dev_url: https://github.com/scikit-build/scikit-build

extra:
  recipe-maintainers:
    - isuruf
    - scopatz
    - jcfr
    - msarahan
