travis:
  secure:
    BINSTAR_TOKEN: jzA0evIq69eUhlk8D8BmT9WDZ6aRntDPO2ojCW/r/tp2Dce8n8jxSEhkbv1Civ36Xssya7rNRtfGfNJV6FIIwV+ZYoHwkqx4PItvMk/sTF622YORK3V2GX+p1LzyxJg12fGKthiHr9t/jruH7dBcqdAIvaVJyi6BBGnAuYgsOiNpbfx8WsScE7Ijevb+2eDsJO6Lc+89EK1GNn4Il2jkaBSg+BeeRtdwU+aoJ/0Z2Qb8VGhs8TPMwAadTlH09A5nnhWU591Sd9OkOGxvCbJQfh/MYacqKSv0Y46TL1oGegXcb36FDXcKrx2fBxZyDD2TZ1pQH3RCh5BA2LRXYwPdRCZEa3Gof8o29W5ZG1s0JKuMdes57TBSMvgQx+pBDC4eFc7+kcgRZelTiHqftEvq1C+KnDTEfq6Fbl4Bz7ZRSNlv7L18/cxYYbcAMvG38Phv5Uw55EBAW3r7em2q/Y/M1FDvHSkMrZSYNIvZWpXHHqMB0EWZH2hRKHaTT9FS8nF/qYThU0s2DZhDYqYC+byHidfSgC9gS1b8XknNb7BVtgONaLQuNcCYcAjtXQ52MnVgFL80qkkJVRAc06iQ7PRifYEkvIhlwmqId3VEDJ5UTpb0plVUUZbGrjIi/AaPOHf4fzsXo/V60BnYoWHxZ0nv1eIEN5SjoibMD2z1Em3YXLI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
